// Code generated by generate_plugins; DO NOT EDIT.
// Generated at: 2025-12-05T10:05:06+01:00
//
// This file contains the list of UMH plugin names, auto-detected from *_plugin
// directories by scanning for service.Register* calls.

package main

// umhPluginNames contains all UMH plugin names.
// Used by detectSource() to determine if a plugin is from benthos-umh or upstream.
var umhPluginNames = map[string]bool{
	"classic_to_core": true,
	"downsampler": true,
	"ethernetip": true,
	"modbus": true,
	"nodered_js": true,
	"opcua": true,
	"s7comm": true,
	"sensorconnect": true,
	"sparkplug_b": true,
	"stream_processor": true,
	"tag_processor": true,
	"topic_browser": true,
	"uns": true,
}
