// Copyright 2025 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by generate_plugins; DO NOT EDIT.
// Generated at: 2025-12-05T11:44:32+01:00
//
// This file contains the list of UMH plugin names, auto-detected from *_plugin
// directories by scanning for service.Register* calls.

package main

// umhPluginNames contains all UMH plugin names.
// Used by detectSource() to determine if a plugin is from benthos-umh or upstream.
var umhPluginNames = map[string]bool{
	"classic_to_core": true,
	"downsampler": true,
	"ethernetip": true,
	"modbus": true,
	"nodered_js": true,
	"opcua": true,
	"s7comm": true,
	"sensorconnect": true,
	"sparkplug_b": true,
	"stream_processor": true,
	"tag_processor": true,
	"topic_browser": true,
	"uns": true,
}
