---
name: Setup Node
description: Setup Node.js and install dependencies.

inputs:
  node_version:
    description: The Node.js version.
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        cache: npm
        node-version: ${{ inputs.node_version }}
    - name: Install dependencies
      shell: bash
      run: npm ci
