---
dist: target/dist

release:
  prerelease: auto

changelog:
  skip: true

signs:
  - artifacts: checksum

builds:
  - id: benthos
    main: cmd/benthos/main.go
    binary: benthos
    goos: [windows, darwin, linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/benthosdev/benthos/v4/internal/cli.Version={{.Version}}
      -X github.com/benthosdev/benthos/v4/internal/cli.DateBuilt={{.Date}}

archives:
  - id: benthos
    builds: [benthos]
    format: tar.gz
    files: [README.md, CHANGELOG.md, LICENSE.txt]
