---
service: benthos-plugin

frameworkVersion: '^2.0.0'

variablesResolutionMode: 20210219
configValidationMode: error

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

plugins:
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    LOG_VERSION: ${file(./package.json):version}

custom:
  domain: makenew.razorx.app
  customDomain:
    domainName: ${sls:stage}.${self:service}.${self:custom.domain}
    endpointType: regional
    createRoute53Record: true
  serverless-offline:
    useDocker: true

functions:
  todo:
    handler: benthos-lambda
    package:
      artifact: dist/todo.zip
    events:
      - http:
          method: get
          path: /todo
