---
service: benthos-plugin

frameworkVersion: '^2.66.2'

variablesResolutionMode: 20210326
configValidationMode: error

plugins:
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  httpApi:
    payload: '2.0'
    disableDefaultEndpoint: true
  apiGateway:
    shouldStartNameWithService: true
  eventBridge:
    useCloudFormation: true
  deploymentBucket:
    blockPublicAccess: true
  lambdaHashingVersion: 20201221
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    LOG_VERSION: ${file(./package.json):version}

custom:
  domain: makenew.razorx.app
  customDomain:
    domainName: ${sls:stage}.${self:service}.${self:custom.domain}
    apiType: http
    endpointType: regional
    createRoute53Record: true
  serverless-offline:
    useDocker: true

package:
  individually: true

functions:
  todo:
    handler: benthos-lambda
    package:
      artifact: dist/todo.zip
    events:
      - httpApi:
          method: get
          path: /todo
