---
service: benthos-plugin

frameworkVersion: '^3.17.0'

configValidationMode: error

provider:
  name: aws
  deploymentMethod: direct
  architecture: arm64
  runtime: provided.al2
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  httpApi:
    payload: '2.0'
    disableDefaultEndpoint: true
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    blockPublicAccess: true
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    LOG_VERSION: ${file(./package.json):version}

package:
  individually: true

functions:
  todo:
    url: true
    handler: benthos-lambda
    package:
      artifact: dist/todo.zip
