// Copyright 2026 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is hand-written and is NOT regenerated by protoc: protoc-gen-go only
// rewrites *.pb.go, so the convenience methods here survive regeneration.

package proto

import "strings"

// LocationPath returns the full location path by joining Level0 with all
// LocationSublevels, e.g. Level0="enterprise" and ["site","area"] -> "enterprise.site.area".
//
// It is defensive so a hand-built TopicInfo still hashes consistently:
//   - a nil receiver returns ""
//   - leading/trailing whitespace is trimmed from every segment, so " enterprise "
//     and "enterprise" produce the same path
//
// For an empty LocationSublevels it returns just Level0.
func (x *TopicInfo) LocationPath() string {
	if x == nil {
		return ""
	}
	base := strings.TrimSpace(x.Level0)
	if len(x.LocationSublevels) == 0 {
		return base
	}
	cleaned := make([]string, 0, len(x.LocationSublevels)+1)
	cleaned = append(cleaned, base)
	for _, s := range x.LocationSublevels {
		cleaned = append(cleaned, strings.TrimSpace(s))
	}
	return strings.Join(cleaned, ".")
}
