// Copyright 2025 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command generate_plugins scans *_plugin directories and generates a Go source
// file listing all UMH plugin names. This enables automatic detection of whether
// a plugin is from benthos-umh or upstream Benthos.
//
// Usage:
//
//	go run ./cmd/tools/generate_plugins [root_dir]
//
// If root_dir is not specified, defaults to current directory.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"time"
)

// registerPatterns matches service.Register* calls to extract plugin names
// Uses (?s) to allow . to match newlines for multi-line registrations
var registerPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?s)service\.RegisterBatchInput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterBatchOutput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterBatchProcessor\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterOutput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterInput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterProcessor\s*\(\s*"([^"]+)"`),
}

const generatedTemplate = `// Copyright 2025 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by generate_plugins; DO NOT EDIT.
// Generated at: {{.Timestamp}}
//
// This file contains the list of UMH plugin names, auto-detected from *_plugin
// directories by scanning for service.Register* calls.

package main

// umhPluginNames contains all UMH plugin names.
// Used by detectSource() to determine if a plugin is from benthos-umh or upstream.
var umhPluginNames = map[string]bool{
{{- range .Plugins}}
	"{{.}}": true,
{{- end}}
}
`

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	plugins, err := findUMHPlugins(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding plugins: %v\n", err)
		os.Exit(1)
	}

	outputPath := filepath.Join(rootDir, "cmd", "schema-export", "umh_plugins_gen.go")
	if err := generateFile(plugins, outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d plugins:\n", outputPath, len(plugins))
	for _, p := range plugins {
		fmt.Printf("  - %s\n", p)
	}
}

func findUMHPlugins(rootDir string) ([]string, error) {
	pluginDirs, err := filepath.Glob(filepath.Join(rootDir, "*_plugin"))
	if err != nil {
		return nil, fmt.Errorf("glob failed: %w", err)
	}

	pluginSet := make(map[string]bool)
	for _, dir := range pluginDirs {
		goFiles, err := filepath.Glob(filepath.Join(dir, "*.go"))
		if err != nil {
			continue
		}
		for _, f := range goFiles {
			// Skip test files
			if strings.HasSuffix(f, "_test.go") {
				continue
			}
			extractPluginNames(f, pluginSet)
		}
	}

	plugins := make([]string, 0, len(pluginSet))
	for p := range pluginSet {
		plugins = append(plugins, p)
	}
	sort.Strings(plugins)
	return plugins, nil
}

func extractPluginNames(filePath string, plugins map[string]bool) {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return
	}

	// Handle both single-line and multi-line registration patterns
	// e.g., service.RegisterBatchInput("opcua", ...) or
	//       service.RegisterBatchInput(\n\t"opcua", ...)
	for _, pattern := range registerPatterns {
		matches := pattern.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) > 1 {
				plugins[match[1]] = true
			}
		}
	}
}

func generateFile(plugins []string, outputPath string) error {
	tmpl, err := template.New("plugins").Parse(generatedTemplate)
	if err != nil {
		return fmt.Errorf("template parse failed: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create file failed: %w", err)
	}
	defer f.Close()

	data := map[string]interface{}{
		"Timestamp": time.Now().Format(time.RFC3339),
		"Plugins":   plugins,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("template execute failed: %w", err)
	}

	return nil
}
