// Copyright 2025 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command generate_plugins scans *_plugin directories and generates a Go source
// file listing all UMH plugin names. This enables automatic detection of whether
// a plugin is from benthos-umh or upstream Benthos.
//
// Usage:
//
//	go run ./cmd/tools/generate_plugins [root_dir]
//
// If root_dir is not specified, defaults to current directory.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// registerPatterns matches service.Register* calls to extract plugin names
// Uses (?s) to allow . to match newlines for multi-line registrations
var registerPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?s)service\.RegisterBatchInput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterBatchOutput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterBatchProcessor\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterOutput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterInput\s*\(\s*"([^"]+)"`),
	regexp.MustCompile(`(?s)service\.RegisterProcessor\s*\(\s*"([^"]+)"`),
}

// templateRegisterPattern detects a template registration in a Go file. Unlike
// the Register* calls above, the template's NAME is not a string literal in the
// Go source — RegisterTemplateYAML/MustRegisterTemplateYAML take a YAML document
// (typically //go:embed'd from a *.yaml in the same plugin dir), and the name
// lives in that YAML's top-level `name:` field. So a Go-file match here only
// flags "this dir registers a template"; the name is then read from the dir's
// template YAML by templateNamePattern below.
var templateRegisterPattern = regexp.MustCompile(`(?:Must)?RegisterTemplateYAML\s*\(`)

// templateNamePattern extracts the top-level `name:` from a benthos template
// YAML (the name benthos registers the template under, e.g. "uns_beta"). Anchored
// to the start of a line so it ignores indented `name:` keys inside nested config
// blocks and only matches the document-level field.
var templateNamePattern = regexp.MustCompile(`(?m)^name:\s*"?([A-Za-z0-9_]+)"?`)

// templateDocPattern matches a benthos template document's top-level `type:`
// field (input/output/processor). Used to distinguish a template YAML from other
// YAML files in a plugin dir before reading its name.
var templateDocPattern = regexp.MustCompile(`(?m)^type:\s*"?(?:input|output|processor)"?`)

const generatedTemplate = `// Copyright 2025 UMH Systems GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by generate_plugins; DO NOT EDIT.
//
// This file contains the list of UMH plugin names, auto-detected from *_plugin
// directories by scanning for service.Register* calls and template YAML name:
// fields. The output is deterministic (no generated-at timestamp) so that a
// re-run is a no-op under "git diff --exit-code" - a drifted commit fails CI.

package main

// umhPluginNames contains all UMH plugin names.
// Used by detectSource() to determine if a plugin is from benthos-umh or upstream.
var umhPluginNames = map[string]bool{
{{- range .Plugins}}
	"{{.}}": true,
{{- end}}
}
`

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	plugins, err := findUMHPlugins(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding plugins: %v\n", err)
		os.Exit(1)
	}

	outputPath := filepath.Join(rootDir, "cmd", "schema-export", "umh_plugins_gen.go")
	if err := generateFile(plugins, outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d plugins:\n", outputPath, len(plugins))
	for _, p := range plugins {
		fmt.Printf("  - %s\n", p)
	}
}

func findUMHPlugins(rootDir string) ([]string, error) {
	pluginDirs, err := filepath.Glob(filepath.Join(rootDir, "*_plugin"))
	if err != nil {
		return nil, fmt.Errorf("glob failed: %w", err)
	}

	pluginSet := make(map[string]bool)
	for _, dir := range pluginDirs {
		goFiles, err := filepath.Glob(filepath.Join(dir, "*.go"))
		if err != nil {
			continue
		}
		registersTemplate := false
		for _, f := range goFiles {
			// Skip test files
			if strings.HasSuffix(f, "_test.go") {
				continue
			}
			extractPluginNames(f, pluginSet)
			if fileRegistersTemplate(f) {
				registersTemplate = true
			}
		}
		// A dir that calls RegisterTemplateYAML registers a template under a name
		// that lives in a template YAML, not in the Go source — read it from the
		// dir's *.yaml template files (the name: field benthos registers under).
		if registersTemplate {
			extractTemplateNames(dir, pluginSet)
		}
	}

	plugins := make([]string, 0, len(pluginSet))
	for p := range pluginSet {
		plugins = append(plugins, p)
	}
	sort.Strings(plugins)
	return plugins, nil
}

func extractPluginNames(filePath string, plugins map[string]bool) {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return
	}

	// Handle both single-line and multi-line registration patterns
	// e.g., service.RegisterBatchInput("opcua", ...) or
	//       service.RegisterBatchInput(\n\t"opcua", ...)
	for _, pattern := range registerPatterns {
		matches := pattern.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) > 1 {
				plugins[match[1]] = true
			}
		}
	}
}

// fileRegistersTemplate reports whether a Go file calls
// (Must)RegisterTemplateYAML. Template-registered plugins (e.g. uns_beta) take
// their name from a YAML document, not a Go string literal, so the Register*
// patterns never see them; this flags the dir for a follow-up YAML name scan.
func fileRegistersTemplate(filePath string) bool {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	return templateRegisterPattern.Match(content)
}

// extractTemplateNames scans the plugin dir's *.yaml files for benthos template
// documents and adds each template's top-level `name:` to plugins. The name is
// the identifier benthos registers the template under (what detectSource sees),
// so it must come from the same YAML the embed/registration loads — not be
// hand-added — to stay generator-truthful.
func extractTemplateNames(dir string, plugins map[string]bool) {
	yamlFiles, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return
	}
	for _, f := range yamlFiles {
		content, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		// Only treat a YAML as a template if it declares `type: input` /
		// `output` / `processor` at the document level — a benthos template
		// document always does, which keeps non-template YAML (e.g. config
		// examples) from contributing stray names.
		if !templateDocPattern.Match(content) {
			continue
		}
		if m := templateNamePattern.FindSubmatch(content); m != nil {
			plugins[string(m[1])] = true
		}
	}
}

func generateFile(plugins []string, outputPath string) error {
	tmpl, err := template.New("plugins").Parse(generatedTemplate)
	if err != nil {
		return fmt.Errorf("template parse failed: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create file failed: %w", err)
	}
	defer f.Close()

	data := map[string]interface{}{
		"Plugins": plugins,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("template execute failed: %w", err)
	}

	return nil
}
