//*
// Copyright (c) 2015, 2018 Cirrus Link Solutions and others
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// SPDX-License-Identifier: EPL-2.0
//
// Contributors:
//   Cirrus Link Solutions - initial implementation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/sparkplug_b_official.proto

package sparkplugb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *uint64                `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Metrics       []*Payload_Metric      `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Seq           *uint64                `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	Uuid          *string                `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Payload) GetMetrics() []*Payload_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Payload) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Payload_Metric struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Alias        *uint64                `protobuf:"varint,2,opt,name=alias" json:"alias,omitempty"`
	Timestamp    *uint64                `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Datatype     *uint32                `protobuf:"varint,4,opt,name=datatype" json:"datatype,omitempty"`
	IsHistorical *bool                  `protobuf:"varint,5,opt,name=is_historical,json=isHistorical" json:"is_historical,omitempty"`
	IsTransient  *bool                  `protobuf:"varint,6,opt,name=is_transient,json=isTransient" json:"is_transient,omitempty"`
	IsNull       *bool                  `protobuf:"varint,7,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	Metadata     *Payload_MetaData      `protobuf:"bytes,8,opt,name=metadata" json:"metadata,omitempty"`
	Properties   *Payload_PropertySet   `protobuf:"bytes,9,opt,name=properties" json:"properties,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Payload_Metric_IntValue
	//	*Payload_Metric_LongValue
	//	*Payload_Metric_FloatValue
	//	*Payload_Metric_DoubleValue
	//	*Payload_Metric_BooleanValue
	//	*Payload_Metric_StringValue
	//	*Payload_Metric_BytesValue
	//	*Payload_Metric_DatasetValue
	//	*Payload_Metric_TemplateValue
	//	*Payload_Metric_ExtensionValue
	Value         isPayload_Metric_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_Metric) Reset() {
	*x = Payload_Metric{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Metric) ProtoMessage() {}

func (x *Payload_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Metric.ProtoReflect.Descriptor instead.
func (*Payload_Metric) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payload_Metric) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Payload_Metric) GetAlias() uint64 {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return 0
}

func (x *Payload_Metric) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Payload_Metric) GetDatatype() uint32 {
	if x != nil && x.Datatype != nil {
		return *x.Datatype
	}
	return 0
}

func (x *Payload_Metric) GetIsHistorical() bool {
	if x != nil && x.IsHistorical != nil {
		return *x.IsHistorical
	}
	return false
}

func (x *Payload_Metric) GetIsTransient() bool {
	if x != nil && x.IsTransient != nil {
		return *x.IsTransient
	}
	return false
}

func (x *Payload_Metric) GetIsNull() bool {
	if x != nil && x.IsNull != nil {
		return *x.IsNull
	}
	return false
}

func (x *Payload_Metric) GetMetadata() *Payload_MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payload_Metric) GetProperties() *Payload_PropertySet {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Payload_Metric) GetValue() isPayload_Metric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Payload_Metric) GetIntValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Payload_Metric) GetLongValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Payload_Metric) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Payload_Metric) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Payload_Metric) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Payload_Metric) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Payload_Metric) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Payload_Metric) GetDatasetValue() *Payload_DataSet {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_DatasetValue); ok {
			return x.DatasetValue
		}
	}
	return nil
}

func (x *Payload_Metric) GetTemplateValue() *Payload_Template {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_TemplateValue); ok {
			return x.TemplateValue
		}
	}
	return nil
}

func (x *Payload_Metric) GetExtensionValue() *Payload_MetricValueExtension {
	if x != nil {
		if x, ok := x.Value.(*Payload_Metric_ExtensionValue); ok {
			return x.ExtensionValue
		}
	}
	return nil
}

type isPayload_Metric_Value interface {
	isPayload_Metric_Value()
}

type Payload_Metric_IntValue struct {
	IntValue uint32 `protobuf:"varint,10,opt,name=int_value,json=intValue,oneof"`
}

type Payload_Metric_LongValue struct {
	LongValue uint64 `protobuf:"varint,11,opt,name=long_value,json=longValue,oneof"`
}

type Payload_Metric_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,12,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_Metric_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,13,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_Metric_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,14,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_Metric_StringValue struct {
	StringValue string `protobuf:"bytes,15,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_Metric_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,oneof"`
}

type Payload_Metric_DatasetValue struct {
	DatasetValue *Payload_DataSet `protobuf:"bytes,17,opt,name=dataset_value,json=datasetValue,oneof"`
}

type Payload_Metric_TemplateValue struct {
	TemplateValue *Payload_Template `protobuf:"bytes,18,opt,name=template_value,json=templateValue,oneof"`
}

type Payload_Metric_ExtensionValue struct {
	ExtensionValue *Payload_MetricValueExtension `protobuf:"bytes,19,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Metric_IntValue) isPayload_Metric_Value() {}

func (*Payload_Metric_LongValue) isPayload_Metric_Value() {}

func (*Payload_Metric_FloatValue) isPayload_Metric_Value() {}

func (*Payload_Metric_DoubleValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BooleanValue) isPayload_Metric_Value() {}

func (*Payload_Metric_StringValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BytesValue) isPayload_Metric_Value() {}

func (*Payload_Metric_DatasetValue) isPayload_Metric_Value() {}

func (*Payload_Metric_TemplateValue) isPayload_Metric_Value() {}

func (*Payload_Metric_ExtensionValue) isPayload_Metric_Value() {}

type Payload_MetaData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsMultiPart     *bool                  `protobuf:"varint,1,opt,name=is_multi_part,json=isMultiPart" json:"is_multi_part,omitempty"`
	ContentType     *string                `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Size            *uint64                `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Seq             *uint64                `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	FileName        *string                `protobuf:"bytes,5,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FileType        *string                `protobuf:"bytes,6,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
	Md5             *string                `protobuf:"bytes,7,opt,name=md5" json:"md5,omitempty"`
	Description     *string                `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payload_MetaData) Reset() {
	*x = Payload_MetaData{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_MetaData) ProtoMessage() {}

func (x *Payload_MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_MetaData.ProtoReflect.Descriptor instead.
func (*Payload_MetaData) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payload_MetaData) GetIsMultiPart() bool {
	if x != nil && x.IsMultiPart != nil {
		return *x.IsMultiPart
	}
	return false
}

func (x *Payload_MetaData) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *Payload_MetaData) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Payload_MetaData) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Payload_MetaData) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *Payload_MetaData) GetFileType() string {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return ""
}

func (x *Payload_MetaData) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *Payload_MetaData) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type Payload_PropertySet struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keys          []string                 `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Values        []*Payload_PropertyValue `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_PropertySet) Reset() {
	*x = Payload_PropertySet{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_PropertySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_PropertySet) ProtoMessage() {}

func (x *Payload_PropertySet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_PropertySet.ProtoReflect.Descriptor instead.
func (*Payload_PropertySet) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Payload_PropertySet) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Payload_PropertySet) GetValues() []*Payload_PropertyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type Payload_PropertyValue struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   *uint32                `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	IsNull *bool                  `protobuf:"varint,2,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Payload_PropertyValue_IntValue
	//	*Payload_PropertyValue_LongValue
	//	*Payload_PropertyValue_FloatValue
	//	*Payload_PropertyValue_DoubleValue
	//	*Payload_PropertyValue_BooleanValue
	//	*Payload_PropertyValue_StringValue
	//	*Payload_PropertyValue_PropertysetValue
	//	*Payload_PropertyValue_PropertysetsValue
	//	*Payload_PropertyValue_ExtensionValue
	Value         isPayload_PropertyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_PropertyValue) Reset() {
	*x = Payload_PropertyValue{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_PropertyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_PropertyValue) ProtoMessage() {}

func (x *Payload_PropertyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_PropertyValue.ProtoReflect.Descriptor instead.
func (*Payload_PropertyValue) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Payload_PropertyValue) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Payload_PropertyValue) GetIsNull() bool {
	if x != nil && x.IsNull != nil {
		return *x.IsNull
	}
	return false
}

func (x *Payload_PropertyValue) GetValue() isPayload_PropertyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Payload_PropertyValue) GetIntValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Payload_PropertyValue) GetLongValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Payload_PropertyValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Payload_PropertyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Payload_PropertyValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Payload_PropertyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Payload_PropertyValue) GetPropertysetValue() *Payload_PropertySet {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_PropertysetValue); ok {
			return x.PropertysetValue
		}
	}
	return nil
}

func (x *Payload_PropertyValue) GetPropertysetsValue() *Payload_PropertySetList {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_PropertysetsValue); ok {
			return x.PropertysetsValue
		}
	}
	return nil
}

func (x *Payload_PropertyValue) GetExtensionValue() *Payload_MetricValueExtension {
	if x != nil {
		if x, ok := x.Value.(*Payload_PropertyValue_ExtensionValue); ok {
			return x.ExtensionValue
		}
	}
	return nil
}

type isPayload_PropertyValue_Value interface {
	isPayload_PropertyValue_Value()
}

type Payload_PropertyValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}

type Payload_PropertyValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}

type Payload_PropertyValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_PropertyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_PropertyValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_PropertyValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_PropertyValue_PropertysetValue struct {
	PropertysetValue *Payload_PropertySet `protobuf:"bytes,9,opt,name=propertyset_value,json=propertysetValue,oneof"`
}

type Payload_PropertyValue_PropertysetsValue struct {
	PropertysetsValue *Payload_PropertySetList `protobuf:"bytes,10,opt,name=propertysets_value,json=propertysetsValue,oneof"`
}

type Payload_PropertyValue_ExtensionValue struct {
	ExtensionValue *Payload_MetricValueExtension `protobuf:"bytes,11,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_PropertyValue_IntValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_LongValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_FloatValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_DoubleValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_BooleanValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_StringValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_PropertysetValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_PropertysetsValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_ExtensionValue) isPayload_PropertyValue_Value() {}

type Payload_PropertySetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Propertyset   []*Payload_PropertySet `protobuf:"bytes,1,rep,name=propertyset" json:"propertyset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_PropertySetList) Reset() {
	*x = Payload_PropertySetList{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_PropertySetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_PropertySetList) ProtoMessage() {}

func (x *Payload_PropertySetList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_PropertySetList.ProtoReflect.Descriptor instead.
func (*Payload_PropertySetList) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Payload_PropertySetList) GetPropertyset() []*Payload_PropertySet {
	if x != nil {
		return x.Propertyset
	}
	return nil
}

type Payload_DataSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumOfColumns  *uint64                `protobuf:"varint,1,opt,name=num_of_columns,json=numOfColumns" json:"num_of_columns,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
	Types         []uint32               `protobuf:"varint,3,rep,name=types" json:"types,omitempty"`
	Rows          []*Payload_DataSet_Row `protobuf:"bytes,4,rep,name=rows" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_DataSet) Reset() {
	*x = Payload_DataSet{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_DataSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_DataSet) ProtoMessage() {}

func (x *Payload_DataSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_DataSet.ProtoReflect.Descriptor instead.
func (*Payload_DataSet) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Payload_DataSet) GetNumOfColumns() uint64 {
	if x != nil && x.NumOfColumns != nil {
		return *x.NumOfColumns
	}
	return 0
}

func (x *Payload_DataSet) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Payload_DataSet) GetTypes() []uint32 {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Payload_DataSet) GetRows() []*Payload_DataSet_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Payload_DataSetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Payload_DataSetValue_IntValue
	//	*Payload_DataSetValue_LongValue
	//	*Payload_DataSetValue_FloatValue
	//	*Payload_DataSetValue_DoubleValue
	//	*Payload_DataSetValue_BooleanValue
	//	*Payload_DataSetValue_StringValue
	//	*Payload_DataSetValue_ExtensionValue
	Value         isPayload_DataSetValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_DataSetValue) Reset() {
	*x = Payload_DataSetValue{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_DataSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_DataSetValue) ProtoMessage() {}

func (x *Payload_DataSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_DataSetValue.ProtoReflect.Descriptor instead.
func (*Payload_DataSetValue) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Payload_DataSetValue) GetValue() isPayload_DataSetValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Payload_DataSetValue) GetIntValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Payload_DataSetValue) GetLongValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Payload_DataSetValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Payload_DataSetValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Payload_DataSetValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Payload_DataSetValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Payload_DataSetValue) GetExtensionValue() *Payload_MetricValueExtension {
	if x != nil {
		if x, ok := x.Value.(*Payload_DataSetValue_ExtensionValue); ok {
			return x.ExtensionValue
		}
	}
	return nil
}

type isPayload_DataSetValue_Value interface {
	isPayload_DataSetValue_Value()
}

type Payload_DataSetValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,1,opt,name=int_value,json=intValue,oneof"`
}

type Payload_DataSetValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,2,opt,name=long_value,json=longValue,oneof"`
}

type Payload_DataSetValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_DataSetValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_DataSetValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,5,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_DataSetValue_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_DataSetValue_ExtensionValue struct {
	ExtensionValue *Payload_MetricValueExtension `protobuf:"bytes,7,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_DataSetValue_IntValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_LongValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_FloatValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_DoubleValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_BooleanValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_StringValue) isPayload_DataSetValue_Value() {}

func (*Payload_DataSetValue_ExtensionValue) isPayload_DataSetValue_Value() {}

type Payload_Template struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Version       *string                       `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Metrics       []*Payload_Metric             `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Parameters    []*Payload_Template_Parameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	TemplateRef   *string                       `protobuf:"bytes,4,opt,name=template_ref,json=templateRef" json:"template_ref,omitempty"`
	IsDefinition  *bool                         `protobuf:"varint,5,opt,name=is_definition,json=isDefinition" json:"is_definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_Template) Reset() {
	*x = Payload_Template{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Template) ProtoMessage() {}

func (x *Payload_Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Template.ProtoReflect.Descriptor instead.
func (*Payload_Template) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Payload_Template) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Payload_Template) GetMetrics() []*Payload_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Payload_Template) GetParameters() []*Payload_Template_Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Payload_Template) GetTemplateRef() string {
	if x != nil && x.TemplateRef != nil {
		return *x.TemplateRef
	}
	return ""
}

func (x *Payload_Template) GetIsDefinition() bool {
	if x != nil && x.IsDefinition != nil {
		return *x.IsDefinition
	}
	return false
}

type Payload_MetricValueExtension struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payload_MetricValueExtension) Reset() {
	*x = Payload_MetricValueExtension{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_MetricValueExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_MetricValueExtension) ProtoMessage() {}

func (x *Payload_MetricValueExtension) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_MetricValueExtension.ProtoReflect.Descriptor instead.
func (*Payload_MetricValueExtension) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 8}
}

type Payload_DataSet_Row struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Elements      []*Payload_DataSetValue `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_DataSet_Row) Reset() {
	*x = Payload_DataSet_Row{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_DataSet_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_DataSet_Row) ProtoMessage() {}

func (x *Payload_DataSet_Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_DataSet_Row.ProtoReflect.Descriptor instead.
func (*Payload_DataSet_Row) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Payload_DataSet_Row) GetElements() []*Payload_DataSetValue {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Payload_Template_Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type  *uint32                `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Payload_Template_Parameter_IntValue
	//	*Payload_Template_Parameter_LongValue
	//	*Payload_Template_Parameter_FloatValue
	//	*Payload_Template_Parameter_DoubleValue
	//	*Payload_Template_Parameter_BooleanValue
	//	*Payload_Template_Parameter_StringValue
	//	*Payload_Template_Parameter_ExtensionValue
	Value         isPayload_Template_Parameter_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_Template_Parameter) Reset() {
	*x = Payload_Template_Parameter{}
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_Template_Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Template_Parameter) ProtoMessage() {}

func (x *Payload_Template_Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sparkplug_b_official_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Template_Parameter.ProtoReflect.Descriptor instead.
func (*Payload_Template_Parameter) Descriptor() ([]byte, []int) {
	return file_proto_sparkplug_b_official_proto_rawDescGZIP(), []int{0, 7, 0}
}

func (x *Payload_Template_Parameter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Payload_Template_Parameter) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Payload_Template_Parameter) GetValue() isPayload_Template_Parameter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Payload_Template_Parameter) GetIntValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Payload_Template_Parameter) GetLongValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Payload_Template_Parameter) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Payload_Template_Parameter) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Payload_Template_Parameter) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Payload_Template_Parameter) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Payload_Template_Parameter) GetExtensionValue() *Payload_MetricValueExtension {
	if x != nil {
		if x, ok := x.Value.(*Payload_Template_Parameter_ExtensionValue); ok {
			return x.ExtensionValue
		}
	}
	return nil
}

type isPayload_Template_Parameter_Value interface {
	isPayload_Template_Parameter_Value()
}

type Payload_Template_Parameter_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}

type Payload_Template_Parameter_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}

type Payload_Template_Parameter_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_Template_Parameter_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_Template_Parameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_Template_Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_Template_Parameter_ExtensionValue struct {
	ExtensionValue *Payload_MetricValueExtension `protobuf:"bytes,9,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Template_Parameter_IntValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_LongValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_FloatValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_DoubleValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_BooleanValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_StringValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_ExtensionValue) isPayload_Template_Parameter_Value() {}

var File_proto_sparkplug_b_official_proto protoreflect.FileDescriptor

const file_proto_sparkplug_b_official_proto_rawDesc = "" +
	"\n" +
	" proto/sparkplug_b_official.proto\x12\x19org.eclipse.tahu.protobuf\"\x94\x1a\n" +
	"\aPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12C\n" +
	"\ametrics\x18\x02 \x03(\v2).org.eclipse.tahu.protobuf.Payload.MetricR\ametrics\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x1a\xf3\x06\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\x04R\x05alias\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bdatatype\x18\x04 \x01(\rR\bdatatype\x12#\n" +
	"\ris_historical\x18\x05 \x01(\bR\fisHistorical\x12!\n" +
	"\fis_transient\x18\x06 \x01(\bR\visTransient\x12\x17\n" +
	"\ais_null\x18\a \x01(\bR\x06isNull\x12G\n" +
	"\bmetadata\x18\b \x01(\v2+.org.eclipse.tahu.protobuf.Payload.MetaDataR\bmetadata\x12N\n" +
	"\n" +
	"properties\x18\t \x01(\v2..org.eclipse.tahu.protobuf.Payload.PropertySetR\n" +
	"properties\x12\x1d\n" +
	"\tint_value\x18\n" +
	" \x01(\rH\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\v \x01(\x04H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\f \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\r \x01(\x01H\x00R\vdoubleValue\x12%\n" +
	"\rboolean_value\x18\x0e \x01(\bH\x00R\fbooleanValue\x12#\n" +
	"\fstring_value\x18\x0f \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x10 \x01(\fH\x00R\n" +
	"bytesValue\x12Q\n" +
	"\rdataset_value\x18\x11 \x01(\v2*.org.eclipse.tahu.protobuf.Payload.DataSetH\x00R\fdatasetValue\x12T\n" +
	"\x0etemplate_value\x18\x12 \x01(\v2+.org.eclipse.tahu.protobuf.Payload.TemplateH\x00R\rtemplateValue\x12b\n" +
	"\x0fextension_value\x18\x13 \x01(\v27.org.eclipse.tahu.protobuf.Payload.MetricValueExtensionH\x00R\x0eextensionValueB\a\n" +
	"\x05value\x1a\xef\x01\n" +
	"\bMetaData\x12\"\n" +
	"\ris_multi_part\x18\x01 \x01(\bR\visMultiPart\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x06 \x01(\tR\bfileType\x12\x10\n" +
	"\x03md5\x18\a \x01(\tR\x03md5\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription*\b\b\t\x10\x80\x80\x80\x80\x02\x1ak\n" +
	"\vPropertySet\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12H\n" +
	"\x06values\x18\x02 \x03(\v20.org.eclipse.tahu.protobuf.Payload.PropertyValueR\x06values\x1a\xc1\x04\n" +
	"\rPropertyValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x17\n" +
	"\ais_null\x18\x02 \x01(\bR\x06isNull\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\rH\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x04 \x01(\x04H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x05 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x06 \x01(\x01H\x00R\vdoubleValue\x12%\n" +
	"\rboolean_value\x18\a \x01(\bH\x00R\fbooleanValue\x12#\n" +
	"\fstring_value\x18\b \x01(\tH\x00R\vstringValue\x12]\n" +
	"\x11propertyset_value\x18\t \x01(\v2..org.eclipse.tahu.protobuf.Payload.PropertySetH\x00R\x10propertysetValue\x12c\n" +
	"\x12propertysets_value\x18\n" +
	" \x01(\v22.org.eclipse.tahu.protobuf.Payload.PropertySetListH\x00R\x11propertysetsValue\x12b\n" +
	"\x0fextension_value\x18\v \x01(\v27.org.eclipse.tahu.protobuf.Payload.MetricValueExtensionH\x00R\x0eextensionValueB\a\n" +
	"\x05value\x1ac\n" +
	"\x0fPropertySetList\x12P\n" +
	"\vpropertyset\x18\x01 \x03(\v2..org.eclipse.tahu.protobuf.Payload.PropertySetR\vpropertyset\x1a\xf7\x01\n" +
	"\aDataSet\x12$\n" +
	"\x0enum_of_columns\x18\x01 \x01(\x04R\fnumOfColumns\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x14\n" +
	"\x05types\x18\x03 \x03(\rR\x05types\x12B\n" +
	"\x04rows\x18\x04 \x03(\v2..org.eclipse.tahu.protobuf.Payload.DataSet.RowR\x04rows\x1aR\n" +
	"\x03Row\x12K\n" +
	"\belements\x18\x01 \x03(\v2/.org.eclipse.tahu.protobuf.Payload.DataSetValueR\belements\x1a\xcf\x02\n" +
	"\fDataSetValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\rH\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x02 \x01(\x04H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12%\n" +
	"\rboolean_value\x18\x05 \x01(\bH\x00R\fbooleanValue\x12#\n" +
	"\fstring_value\x18\x06 \x01(\tH\x00R\vstringValue\x12b\n" +
	"\x0fextension_value\x18\a \x01(\v27.org.eclipse.tahu.protobuf.Payload.MetricValueExtensionH\x00R\x0eextensionValueB\a\n" +
	"\x05value\x1a\xff\x04\n" +
	"\bTemplate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12C\n" +
	"\ametrics\x18\x02 \x03(\v2).org.eclipse.tahu.protobuf.Payload.MetricR\ametrics\x12U\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v25.org.eclipse.tahu.protobuf.Payload.Template.ParameterR\n" +
	"parameters\x12!\n" +
	"\ftemplate_ref\x18\x04 \x01(\tR\vtemplateRef\x12#\n" +
	"\ris_definition\x18\x05 \x01(\bR\fisDefinition\x1a\xf4\x02\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\rH\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x04 \x01(\x04H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x05 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x06 \x01(\x01H\x00R\vdoubleValue\x12%\n" +
	"\rboolean_value\x18\a \x01(\bH\x00R\fbooleanValue\x12#\n" +
	"\fstring_value\x18\b \x01(\tH\x00R\vstringValue\x12b\n" +
	"\x0fextension_value\x18\t \x01(\v27.org.eclipse.tahu.protobuf.Payload.MetricValueExtensionH\x00R\x0eextensionValueB\a\n" +
	"\x05value\x1a \n" +
	"\x14MetricValueExtension*\b\b\x01\x10\x80\x80\x80\x80\x02By\n" +
	"\x19org.eclipse.tahu.protobufB\x0fSparkplugBProtoZKgithub.com/united-manufacturing-hub/benthos-umh/sparkplug_plugin/sparkplugb"

var (
	file_proto_sparkplug_b_official_proto_rawDescOnce sync.Once
	file_proto_sparkplug_b_official_proto_rawDescData []byte
)

func file_proto_sparkplug_b_official_proto_rawDescGZIP() []byte {
	file_proto_sparkplug_b_official_proto_rawDescOnce.Do(func() {
		file_proto_sparkplug_b_official_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sparkplug_b_official_proto_rawDesc), len(file_proto_sparkplug_b_official_proto_rawDesc)))
	})
	return file_proto_sparkplug_b_official_proto_rawDescData
}

var file_proto_sparkplug_b_official_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_sparkplug_b_official_proto_goTypes = []any{
	(*Payload)(nil),                      // 0: org.eclipse.tahu.protobuf.Payload
	(*Payload_Metric)(nil),               // 1: org.eclipse.tahu.protobuf.Payload.Metric
	(*Payload_MetaData)(nil),             // 2: org.eclipse.tahu.protobuf.Payload.MetaData
	(*Payload_PropertySet)(nil),          // 3: org.eclipse.tahu.protobuf.Payload.PropertySet
	(*Payload_PropertyValue)(nil),        // 4: org.eclipse.tahu.protobuf.Payload.PropertyValue
	(*Payload_PropertySetList)(nil),      // 5: org.eclipse.tahu.protobuf.Payload.PropertySetList
	(*Payload_DataSet)(nil),              // 6: org.eclipse.tahu.protobuf.Payload.DataSet
	(*Payload_DataSetValue)(nil),         // 7: org.eclipse.tahu.protobuf.Payload.DataSetValue
	(*Payload_Template)(nil),             // 8: org.eclipse.tahu.protobuf.Payload.Template
	(*Payload_MetricValueExtension)(nil), // 9: org.eclipse.tahu.protobuf.Payload.MetricValueExtension
	(*Payload_DataSet_Row)(nil),          // 10: org.eclipse.tahu.protobuf.Payload.DataSet.Row
	(*Payload_Template_Parameter)(nil),   // 11: org.eclipse.tahu.protobuf.Payload.Template.Parameter
}
var file_proto_sparkplug_b_official_proto_depIdxs = []int32{
	1,  // 0: org.eclipse.tahu.protobuf.Payload.metrics:type_name -> org.eclipse.tahu.protobuf.Payload.Metric
	2,  // 1: org.eclipse.tahu.protobuf.Payload.Metric.metadata:type_name -> org.eclipse.tahu.protobuf.Payload.MetaData
	3,  // 2: org.eclipse.tahu.protobuf.Payload.Metric.properties:type_name -> org.eclipse.tahu.protobuf.Payload.PropertySet
	6,  // 3: org.eclipse.tahu.protobuf.Payload.Metric.dataset_value:type_name -> org.eclipse.tahu.protobuf.Payload.DataSet
	8,  // 4: org.eclipse.tahu.protobuf.Payload.Metric.template_value:type_name -> org.eclipse.tahu.protobuf.Payload.Template
	9,  // 5: org.eclipse.tahu.protobuf.Payload.Metric.extension_value:type_name -> org.eclipse.tahu.protobuf.Payload.MetricValueExtension
	4,  // 6: org.eclipse.tahu.protobuf.Payload.PropertySet.values:type_name -> org.eclipse.tahu.protobuf.Payload.PropertyValue
	3,  // 7: org.eclipse.tahu.protobuf.Payload.PropertyValue.propertyset_value:type_name -> org.eclipse.tahu.protobuf.Payload.PropertySet
	5,  // 8: org.eclipse.tahu.protobuf.Payload.PropertyValue.propertysets_value:type_name -> org.eclipse.tahu.protobuf.Payload.PropertySetList
	9,  // 9: org.eclipse.tahu.protobuf.Payload.PropertyValue.extension_value:type_name -> org.eclipse.tahu.protobuf.Payload.MetricValueExtension
	3,  // 10: org.eclipse.tahu.protobuf.Payload.PropertySetList.propertyset:type_name -> org.eclipse.tahu.protobuf.Payload.PropertySet
	10, // 11: org.eclipse.tahu.protobuf.Payload.DataSet.rows:type_name -> org.eclipse.tahu.protobuf.Payload.DataSet.Row
	9,  // 12: org.eclipse.tahu.protobuf.Payload.DataSetValue.extension_value:type_name -> org.eclipse.tahu.protobuf.Payload.MetricValueExtension
	1,  // 13: org.eclipse.tahu.protobuf.Payload.Template.metrics:type_name -> org.eclipse.tahu.protobuf.Payload.Metric
	11, // 14: org.eclipse.tahu.protobuf.Payload.Template.parameters:type_name -> org.eclipse.tahu.protobuf.Payload.Template.Parameter
	7,  // 15: org.eclipse.tahu.protobuf.Payload.DataSet.Row.elements:type_name -> org.eclipse.tahu.protobuf.Payload.DataSetValue
	9,  // 16: org.eclipse.tahu.protobuf.Payload.Template.Parameter.extension_value:type_name -> org.eclipse.tahu.protobuf.Payload.MetricValueExtension
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_sparkplug_b_official_proto_init() }
func file_proto_sparkplug_b_official_proto_init() {
	if File_proto_sparkplug_b_official_proto != nil {
		return
	}
	file_proto_sparkplug_b_official_proto_msgTypes[1].OneofWrappers = []any{
		(*Payload_Metric_IntValue)(nil),
		(*Payload_Metric_LongValue)(nil),
		(*Payload_Metric_FloatValue)(nil),
		(*Payload_Metric_DoubleValue)(nil),
		(*Payload_Metric_BooleanValue)(nil),
		(*Payload_Metric_StringValue)(nil),
		(*Payload_Metric_BytesValue)(nil),
		(*Payload_Metric_DatasetValue)(nil),
		(*Payload_Metric_TemplateValue)(nil),
		(*Payload_Metric_ExtensionValue)(nil),
	}
	file_proto_sparkplug_b_official_proto_msgTypes[4].OneofWrappers = []any{
		(*Payload_PropertyValue_IntValue)(nil),
		(*Payload_PropertyValue_LongValue)(nil),
		(*Payload_PropertyValue_FloatValue)(nil),
		(*Payload_PropertyValue_DoubleValue)(nil),
		(*Payload_PropertyValue_BooleanValue)(nil),
		(*Payload_PropertyValue_StringValue)(nil),
		(*Payload_PropertyValue_PropertysetValue)(nil),
		(*Payload_PropertyValue_PropertysetsValue)(nil),
		(*Payload_PropertyValue_ExtensionValue)(nil),
	}
	file_proto_sparkplug_b_official_proto_msgTypes[7].OneofWrappers = []any{
		(*Payload_DataSetValue_IntValue)(nil),
		(*Payload_DataSetValue_LongValue)(nil),
		(*Payload_DataSetValue_FloatValue)(nil),
		(*Payload_DataSetValue_DoubleValue)(nil),
		(*Payload_DataSetValue_BooleanValue)(nil),
		(*Payload_DataSetValue_StringValue)(nil),
		(*Payload_DataSetValue_ExtensionValue)(nil),
	}
	file_proto_sparkplug_b_official_proto_msgTypes[11].OneofWrappers = []any{
		(*Payload_Template_Parameter_IntValue)(nil),
		(*Payload_Template_Parameter_LongValue)(nil),
		(*Payload_Template_Parameter_FloatValue)(nil),
		(*Payload_Template_Parameter_DoubleValue)(nil),
		(*Payload_Template_Parameter_BooleanValue)(nil),
		(*Payload_Template_Parameter_StringValue)(nil),
		(*Payload_Template_Parameter_ExtensionValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sparkplug_b_official_proto_rawDesc), len(file_proto_sparkplug_b_official_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sparkplug_b_official_proto_goTypes,
		DependencyIndexes: file_proto_sparkplug_b_official_proto_depIdxs,
		MessageInfos:      file_proto_sparkplug_b_official_proto_msgTypes,
	}.Build()
	File_proto_sparkplug_b_official_proto = out.File
	file_proto_sparkplug_b_official_proto_goTypes = nil
	file_proto_sparkplug_b_official_proto_depIdxs = nil
}
