---
name: Setup Go.
description: Setup Go.

inputs:
  go_version:
    description: The Go version
    required: false
    default: '1.18'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        restore-keys: |
          ${{ runner.os }}-go-
