# Complete Sparkplug B Primary Host Configuration for UMH
# This configuration connects to a Sparkplug B MQTT broker as a Primary Host,
# processes the data through tag_processor for UMH format conversion,
# and outputs to UMH-formatted MQTT.

input:
  sparkplug_b:
    # MQTT Transport Configuration
    mqtt:
      urls: ["tcp://broker.hivemq.com:1883"]
      client_id: "benthos-umh-primary-host"
      qos: 1
      keep_alive: "60s"
      connect_timeout: "30s"
      clean_session: true
    
    # Identity Configuration
    identity:
      group_id: "TestGroup"
      edge_node_id: "PrimaryHost"
    
    # Role Configuration - Primary Host
    role: "primary_host"
    
    # Subscription Configuration - listen to only TestGroup
    subscription:
      groups: ["TestGroup"]

output:
  stdout: {}