# Complete Sparkplug B Primary Host Configuration for UMH
# This configuration connects to a Sparkplug B MQTT broker as a Primary Host,
# processes the data through tag_processor for UMH format conversion,
# and outputs to UMH-formatted MQTT.
# LISTENS FOR PARRIS METHOD GENERATED EON NODE IDs

# Enable debug logging to see alias resolution
logger:
  level: DEBUG
  format: logfmt

input:
  sparkplug_b:
    # MQTT Transport Configuration
    mqtt:
      urls: ["tcp://broker.hivemq.com:1883"]
      client_id: "benthos-umh-primary-host-parris"
      qos: 1
      keep_alive: "60s"
      connect_timeout: "30s"
      clean_session: true
    
    # Identity Configuration
    identity:
      group_id: "TestGroup"
      edge_node_id: "PrimaryHost"
    
    # Role Configuration - Primary Host
    role: "primary_host"
    
    # Subscription Configuration - listen to TestGroup
    # Will receive messages from EON Node ID: "enterprise:factory:line1:station1"
    subscription:
      groups: ["TestGroup"]

output:
  broker:
    outputs:
      - stdout: {}
      # Uncomment to send to UMH MQTT broker
      # - mqtt:
      #     urls: ["tcp://localhost:1883"]
      #     topic: "umh/v1/enterprise/factory/line1/station1"