# Sparkplug B Edge Node Test Configuration
# This configuration creates a simple Edge Node that publishes test data
# to demonstrate the complete Sparkplug B flow with the Primary Host

input:
  # Generate test data every 5 seconds
  generate:
    interval: "5s"
    mapping: |
      root = {
        "temperature": random() * 100,
        "pressure": random() * 50 + 10,
        "humidity": random() * 100,
        "status": if random() > 0.8 { "alarm" } else { "normal" },
        "counter": counter()
      }

pipeline:
  processors:
    # Add timestamp
    - mapping: |
        root = this
        root.timestamp = now()

output:
  sparkplug_b:
    # MQTT connection to same broker as Primary Host
    mqtt:
      urls: ["tcp://broker.hivemq.com:1883"]
      client_id: "benthos-test-edge-node"
      qos: 1
      keep_alive: "60s"
      connect_timeout: "30s"
      clean_session: true
    
    # Edge Node identity
    identity:
      group_id: "TestGroup"
      edge_node_id: "TestEdgeNode"
    
    # Configure as Edge Node (publishes data)
    role: "edge_node"
    
    # Behavior settings
    behaviour:
      # Send BIRTH message on startup
      send_birth_on_connect: true
      
      # Birth message interval (rebirth every 10 minutes for testing)
      birth_interval: "600s"
      
      # Include sequence numbers
      include_sequence_numbers: true
      
      # Use aliases to optimize payload size
      use_aliases: true

# Optional: Log to see what's being published
logger:
  level: "INFO"
  format: "json" 