# Copyright 2025 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sparkplug B Primary Host Configuration - Minimal Setup
# Subscribes to all Sparkplug B messages and displays them
# Requires: docker run -d --name mosquitto -p 1883:1883 eclipse-mosquitto:1.6

input:
  sparkplug_b:
    mqtt:
      urls: ["tcp://localhost:1883"]
    identity:
      group_id: "DeviceLevelTest"
      edge_node_id: "PrimaryHost"
    role: "primary_host"

output:
  stdout: {}

logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
