input:
  opcua:
    endpoint: "opc.tcp://localhost:50000"
    nodeIDs:
      - "ns=3;s=OpcPlc"
    subscribeEnabled: true
    deadbandType: "percent"     # Percent filtering
    deadbandValue: 2.0          # 2% of EURange
    queueSize: 1
    samplingInterval: 1000

output:
  stdout:
    codec: lines

logger:
  level: INFO
