input:
  opcua:
    endpoint: "opc.tcp://localhost:50000"
    nodeIDs:
      - "i=85"  # Objects folder - standard root
    subscribeEnabled: false  # Just browse, don't subscribe
    queueSize: 1

output:
  stdout:
    codec: lines

logger:
  level: DEBUG
