input:
  opcua:
    endpoint: "opc.tcp://localhost:50000"
    nodeIDs:
      - "ns=3;s=OpcPlc"
    subscribeEnabled: true
    deadbandType: "none"        # Baseline - no filtering
    deadbandValue: 0.0
    queueSize: 1
    samplingInterval: 1000

output:
  stdout:
    codec: lines

logger:
  level: INFO
