agent:
  metricsPort: 8080

benthos:
  - name: hello-world
    desiredState: active
    benthosServiceConfig:
      input:
        generate:
          mapping: root = "hello world from Benthos!" 
          interval: 2s # Output every 2 seconds
          count: 0 # Set to 0 for unlimited messages
      output:
        stdout: {} 