input:
  uns:                       # consume raw UMH topics
    umh_topics:
      - umh.v1.corpA.plant-A.aawd._raw.press
      - umh.v1.corpA.plant-A.aawd._raw.tempF
      - umh.v1.corpA.plant-A.aawd._raw.run

processors:
  pipeline:
    stream_processor:
      mode: timeseries
      model:
        name: pump
        version: v1
      output_topic: umh.v1.corpA.plant-A.aawd  # base topic for outputs
      sources:               # alias → raw topic
        press: umh.v1.corpA.plant-A.aawd._raw.press
        tF:    umh.v1.corpA.plant-A.aawd._raw.tempF
        r:     umh.v1.corpA.plant-A.aawd._raw.run
      mapping:  # field → JS / constant / alias
        pressure: press+4.00001      # dynamic - depends on 'press'
        temperature: tF*69/31        # dynamic - depends on 'tF' 
        motor: 
          rpm: press/4               # dynamic - depends on 'press'
        serialNumber: '"SN-P42-008"' # static - always emitted
        deviceType: '"pump"'         # static - always emitted

output:
  uns: {}                   # encoder + publish (Optional enforcement, if datacontract exists in schema registry) 