---
name: format

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch:
    types:
      - format

jobs:
  fix:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: ${{ secrets.GIT_USER_NAME }}
          git_committer_email: ${{ secrets.GIT_USER_EMAIL }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Go Format
        run: make format
      - name: Format
        run: npm run format
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run format
          commit_user_name: ${{ secrets.GIT_USER_NAME }}
          commit_user_email: ${{ secrets.GIT_USER_EMAIL }}
          commit_author: ${{ secrets.GIT_USER_NAME }} <${{ secrets.GIT_USER_EMAIL }}>
