# Copyright 2023 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: modbus-plc

on:
  push:
    branches:
      - '**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.23.0'

concurrency:
  group: modbus-plc-test
  cancel-in-progress: true

jobs:
  go-test-modbus-plc:
    runs-on:
      group: arc-runners
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          go_version: ${{ env.GO_VERSION }}
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.19.0
      - name: Install Tcping
        run: go install github.com/cloverstd/tcping@v0.1.1

      - name: Check Wago-Modbus port availability
        id: check_wago
        run: |
          set +x
          ENDPOINT="${{ secrets.TEST_WAGO_MODBUS_ENDPOINT }}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_WAGO_MODBUS_ENDPOINT=${{ secrets.TEST_WAGO_MODBUS_ENDPOINT }}" >> "$GITHUB_ENV"
            echo "using Wago-main device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Wago-Modbus-fallback port availability
        id: wago_fallback
        if: ${{ steps.check_wago.outputs.available  == 'false' }}
        run: |
          set +x
          ENDPOINT="${{ secrets.TEST_WAGO_MODBUS_ENDPOINT_FALLBACK }}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_WAGO_MODBUS_ENDPOINT=${{ secrets.TEST_WAGO_MODBUS_ENDPOINT_FALLBACK }}" >> "$GITHUB_ENV"
            echo "using Wago-fallback device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Test
        run: |
          if [ -z "$TEST_WAGO_MODBUS_ENDPOINT" ]; then
            echo "no Wago device available for testing"
            exit 1
          fi
          make test
