---
name: publish

on:
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  registry:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version
        uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: return context.ref.split('/')[2].substring(1)
      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          registry_domain: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GH_TOKEN }}
      - name: Build and push ${{ github.repository }}:${{ steps.version.outputs.result }}
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.result }}
